baseURL = 'https://blogbot.jc-maldo-be.workers.dev/'
languageCode = 'en-us'
title = 'LLMCraft'

[params]
  description = 'LLMCraft — AI / LLM / GenAI engineering blog'

[permalinks]
  posts = '/posts/:slug/'
